versio: 3.8
services:
  postgres:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hard-qode
  backend:
    build: ./src
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers=4 --bind 0.0.0.0:8000 server.wsgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./src/.env.dev

volumes:
  postgres_data: